name: nntu_map
version: 0.2.0+24
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  animated_toggle_switch: ^0.8.2
  photo_view: ^0.15.0
  flex_color_scheme: ^7.2.0
  url_launcher: ^6.1.12
  package_info_plus: ^8.0.0
  crystal_navigation_bar: ^1.0.0
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  get: 4.6.6
  http: 1.2.1
  path_provider: ^2.1.3
  settings_ui: ^2.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.2.0
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/icon.png 
    - assets/navigate/1/
    - assets/navigate/2/
    - assets/navigate/3/
    - assets/navigate/4/
    - assets/navigate/5/
    - assets/navigate/6/
  uses-material-design: true

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.png
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: assets/icon/icon.png
  ios: true
  min_sdk_android: 21

